import socket
from cryptography.fernet import Fernet

# Replace with the key generated by the server
key = b'3XOOofv8LbWJ7rmx8sXGfXWy6LlQHnEIH9fNFXGqkGM='  # Update with the actual key you copied from server.py
cipher_suite = Fernet(key)

def secure_client():
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as client_socket:
        client_socket.connect(('localhost', 65431))  # Connect to the proxy, not the server
        message = "Hello, SCADA!"  # Message to send
        encrypted_message = cipher_suite.encrypt(message.encode())  # Encrypt the message
        client_socket.sendall(encrypted_message)  # Send the encrypted message
        print("Message sent.")

if __name__ == "__main__":
    secure_client()
